Audits: {Avg Ball Time: '0:06', Avg Extra Balls: 0, Avg Game Time: '1:05', Avg Score: 282003,
  Balls Played: 822, Games Played: 274, Games Started: 191}
ClassicHighScoreData:
- {date: 'Fri Jan 31 14:46:41 2014', inits: JELMAR, score: 863100}
- {date: 'Fri Jan 31 14:40:45 2014', inits: LONIT, score: 799010}
- {date: 'Fri Mar 07 11:29:00 2014', inits: KPQRS, score: 700000}
- {date: 'Fri Jan 31 14:57:09 2014', inits: DIONNE, score: 604100}
- {date: 'Fri Jan 31 14:40:45 2014', inits: TIBE, score: 389410}
